
import os

src = r"d:\HoangLam\MMO\tht-global\en\company-incorporation\singapore.html"
dst = r"d:\HoangLam\MMO\tht-global\vi\thanh-lap-cong-ty-singapore.html"

replacements = {
    '<title>Singapore Company Incorporation | THT Global</title>': '<title>Thành lập công ty tại Singapore | THT Global</title>',
    'Establish your presence in Southeast Asia\'s': 'Khẳng định vị thế doanh nghiệp tại trung tâm',
    'financial hub': 'tài chính Đông Nam Á',
    'Contact our expert today!': 'Liên hệ chuyên gia ngay!',
    'Explore Details': 'Xem chi tiết',
    'Why incorporate in Singapore with THT': 'Tại sao nên thành lập công ty tại Singapore cùng THT',
    'Global?': 'Global?',
    '100% company ownership for foreign': '100% quyền sở hữu công ty cho',
    'entrepreneurs.': 'doanh nhân nước ngoài.',
    '100% online, quick, and legal procedures:': 'Thủ tục 100% trực tuyến, nhanh chóng và hợp pháp:',
    'Fast Singapore company registration.': 'Đăng ký công ty Singapore nhanh chóng.',
    'Straightforward Singapore company': 'Dịch vụ quản trị công ty Singapore',
    'administration service.': 'đơn giản và minh bạch.',
    'Easy capital increase and share': 'Dễ dàng tăng vốn và phát hành',
    'issuance.': 'cổ phiếu.',
    '100% safe online banking transactions in': 'Giao dịch ngân hàng trực tuyến an toàn 100% tại',
    'this proactive global financial center.': 'trung tâm tài chính toàn cầu năng động này.',
    'Irresistible low Singapore corporate': 'Thuế thu nhập doanh nghiệp thấp',
    'income tax rate:': 'tại Singapore:',
    'Attractive corporate income tax': 'Ưu đãi thuế thu nhập doanh nghiệp',
    'incentives for both registered': 'hấp dẫn cho cả công ty mới đăng ký',
    'companies and startups.': 'và các startup.',
    'Double tax avoidance agreements with': 'Hiệp định tránh đánh thuế hai lần với',
    '+70 countries.': 'hơn 70 quốc gia.',
    'Strategic geographical location, a bridge': 'Vị trí địa lý chiến lược, cầu nối',
    'between Southeast Asian nations, and a': 'giữa các quốc gia Đông Nam Á và',
    'connection between Asia and the rest of the': 'kết nối giữa Châu Á và phần còn lại của',
    'world.': 'thế giới.',
    'We handle incorporation, company secretary': 'Chúng tôi lo liệu việc thành lập, thư ký',
    'services, and annual return filings.': 'công ty và nộp báo cáo thường niên.',
    '1 fully compliant Singapore company;': '1 công ty Singapore tuân thủ đầy đủ;',
    '1 company bank account;': '1 tài khoản ngân hàng doanh nghiệp;',
    '1 professionally designed website meeting': '1 trang web thiết kế chuyên nghiệp đạt',
    'international standards, with only the': 'chuẩn quốc tế, chỉ với phí hosting.',
    'hosting fees.': '',
    'Unlimited consultation time;': 'Thời gian tư vấn không giới hạn;',
    '1-1 consultations from our experts in tax': 'Tư vấn 1-1 từ các chuyên gia thuế',
    'and accounting matters.': 'và kế toán của chúng tôi.',
    'The': 'Điểm đến',
    '<span': '<span', # Context
    'perfect': 'hoàn hảo',
    'destination for all business needs': 'cho mọi nhu cầu kinh doanh',
    'Why choose Singapore?': 'Tại sao chọn Singapore?',
    'A-Z company registration': 'Đăng ký công ty A-Z',
    'Bank account': 'Tài khoản ngân hàng',
    'Taxation and accounting': 'Thuế và kế toán',
    'A-to-Z Singapore company registration for': 'Đăng ký công ty Singapore trọn gói cho',
    'foreigners': 'người nước ngoài',
    'Your Singapore company setup process': 'Quy trình thành lập công ty Singapore của bạn',
    'varies based on your residency status,': 'phụ thuộc vào tình trạng cư trú,',
    'Whether you are a foreigner or a foreign': 'Dù bạn là người nước ngoài hay công ty nước ngoài,',
    'company, we offer the same professional,': 'chúng tôi đều cung cấp sự hỗ trợ chuyên nghiệp,',
    'comprehensive support for seamless': 'toàn diện cho việc thành lập công ty',
    'Singapore company incorporation.': 'tại Singapore.',
    'Is this your business portrait?': 'Đây có phải là chân dung doanh nghiệp của bạn?',
    'Don&#039;t worry, we are here to assist you in': 'Đừng lo lắng, chúng tôi ở đây để hỗ trợ bạn',
    'resolving challenging issues for businesses.': 'giải quyết các vấn đề khó khăn của doanh nghiệp.',
    'Talk to expert now!': 'Trao đổi với chuyên gia ngay!',
    'Your comprehensive Singapore company': 'Dịch vụ đăng ký công ty Singapore',
    'registration service with': 'toàn diện với',
    'no hidden fees': 'không phí ẩn',
    'For aspiring foreign entrepreneurs and': 'Dành cho doanh nhân và công ty',
    'foreign companies.': 'nước ngoài.',
    'Check and register the company name.': 'Kiểm tra và đăng ký tên công ty.',
    'Set up a company in Singapore (including': 'Thành lập công ty tại Singapore (bao gồm',
    'fee payable with Singapore’s company': 'phí nộp cho cơ quan đăng ký kinh doanh',
    'registrar, Accounting and Corporate': 'Singapore, ACRA).',
    'Regulatory Authority (ACRA).': '',
    'Prepare company incorporation document:': 'Chuẩn bị hồ sơ thành lập công ty:',
    'business profile, company constitution,': 'hồ sơ kinh doanh, điều lệ công ty,',
    'director profile, etc.': 'hồ sơ giám đốc, v.v.',
    'Full-compliant Nominee director and': 'Giám đốc chỉ định tuân thủ đầy đủ và',
    'Corporate Secretary services': 'dịch vụ Thư ký Công ty',
    'Registered company addresses service to your': 'Dịch vụ địa chỉ đăng ký công ty theo',
    'business needs': 'nhu cầu doanh nghiệp',
    'Bank account opening services at physical': 'Dịch vụ mở tài khoản ngân hàng tại',
    'and digital banks': 'ngân hàng vật lý và kỹ thuật số',
    'Singapore accounting, tax-filing, annual': 'Dịch vụ kế toán, kê khai thuế, báo cáo',
    'filing service': 'thường niên tại Singapore',
    'Open your corporate bank account with 99%': 'Mở tài khoản ngân hàng doanh nghiệp với 99%',
    'success': 'thành công',
    'We take pride in providing a unique bank': 'Chúng tôi tự hào cung cấp dịch vụ mở',
    'account opening service exclusively for': 'tài khoản ngân hàng độc quyền dành cho',
    'companies in Singapore.': 'các công ty tại Singapore.',
    'Our service is designed to offer you a': 'Dịch vụ của chúng tôi mang lại trải nghiệm',
    'seamless experience, and excellent support': 'liền mạch và hỗ trợ tuyệt vời để',
    'for opening bank accounts tailored to your': 'mở tài khoản ngân hàng phù hợp với',
    'company needs.': 'nhu cầu công ty.',
    'Physical bank accounts': 'Tài khoản ngân hàng vật lý',
    'Digital bank accounts': 'Tài khoản ngân hàng số',
    'Accounting, tax filing, and financial': 'Dịch vụ kế toán, thuế và báo cáo tài chính',
    'reporting service for your Singapore company': 'cho công ty Singapore của bạn',
    'with professionalism and accuracy': 'với sự chuyên nghiệp và chính xác',
    'With a team of experienced accountants and': 'Với đội ngũ kế toán giàu kinh nghiệm và',
    'profound knowledge in Singapore accounting': 'kiến thức sâu rộng về chuẩn mực kế toán',
    'standards (SFRS) and the local tax system,': 'Singapore (SFRS) và hệ thống thuế,',
    'you can expect our unwavering commitment and': 'bạn có thể tin tưởng vào cam kết và',
    'high-quality service in addressing tax and': 'dịch vụ chất lượng cao trong việc giải quyết',
    'corporate accounting issues seamlessly.': 'các vấn đề thuế và kế toán doanh nghiệp.',
    'Preparation of financial reports in': 'Chuẩn bị báo cáo tài chính tuân thủ',
    'adherence to Singapore accounting': 'chuẩn mực kế toán Singapore',
    'standards': '',
    'Tax consulting services involving direct': 'Dịch vụ tư vấn thuế bao gồm làm việc',
    'collaboration with the Singapore tax': 'trực tiếp với cơ quan thuế Singapore',
    'department': '',
    'English-Vietnamese support in both': 'Hỗ trợ tiếng Anh-Việt tại cả',
    'Singapore and Vietnam': 'Singapore và Việt Nam',
    'THT Global is ready to help': 'THT Global sẵn sàng giúp đỡ',
    'Let THT Global help you set up and manage': 'Hãy để THT Global giúp bạn thành lập và',
    'your overseas company from A to Z so that': 'quản lý công ty nước ngoài từ A đến Z để',
    'you can focus on global ambitions and create': 'bạn có thể tập trung vào tham vọng toàn cầu',
    'business': 'và tạo ra sự',
    'breakthroughs': 'đột phá trong kinh doanh',
    'More than 700 business owners have chosen': 'Hơn 700 chủ doanh nghiệp đã chọn',
    'THT Global as their strategic consulting': 'THT Global làm đối tác tư vấn chiến lược',
    'partner for a successful company': 'để thành lập và quản lý công ty',
    'incorporation and management. And so can you': 'thành công. Bạn cũng có thể như vậy.',
    'too. Contact our expert and start your': 'Liên hệ chuyên gia của chúng tôi và bắt đầu',
    'journey today.': 'hành trình ngay hôm nay.',
    'Contact our experts and enjoy unlimited': 'Liên hệ chuyên gia và hưởng',
    'benefits today!': 'quyền lợi không giới hạn ngay!',
    'Contact Us now': 'Liên hệ ngay',
    'News and Articles': 'Tin Tức & Bài Viết',
    'Want to deep dive into the Singapore company': 'Muốn tìm hiểu sâu về môi trường kinh doanh',
    'landscape? We got you covered! Get all the': 'Singapore? Chúng tôi có tin tức cho bạn!',
    'information you need in our article section': 'Cập nhật thông tin mới nhất tại mục',
    'which gets updated constantly.': 'bài viết của chúng tôi.',
    # Menu translations
    '>About Us<': '>Về Chúng Tôi<',
    '>Our Story<': '>Câu Chuyện Của Chúng Tôi<',
    '>Global Network<': '>Mạng Lưới Toàn Cầu<',
    '>Corporate Services<': '>Dịch Vụ Doanh Nghiệp<',
    '>Singapore Company Formation<': '>Thành lập công ty tại Singapore<',
    '>US Company Formation<': '>Thành lập công ty tại Mỹ<',
    '>HK Company Formation<': '>Thành lập công ty tại Hồng Kông<',
    '>China & Korea Market Entry<': '>Thâm nhập thị trường Trung Quốc & Hàn Quốc<',
    '>Accounting & Payment Solutions<': '>Giải pháp Kế toán & Thanh toán<',
    '>Logistics & Export<': '>Logistics & Xuất Khẩu<',
    '>Sourcing & Import<': '>Mua Hộ & Nhập Khẩu<',
    '>Tracking (Tool)<': '>Tra Cứu (Công Cụ)<',
    '>Contact Us<': '>Liên Hệ<',
     # Footer
    'Helpful Links': 'Liên kết hữu ích',
    'Useful information': 'Thông tin hữu ích',
    'Payment': 'Thanh toán',
    'Office address': 'Địa chỉ văn phòng',
    'Viet Nam': 'Việt Nam',
    'Hong Kong': 'Hồng Kông',
    'USA': 'Mỹ',
}

link_map = {
    'href="../about-us.html"': 'href="ve-chung-toi.html"',
    'href="../our-story.html"': 'href="cau-chuyen-cua-chung-toi.html"',
    'href="../global-network.html"': 'href="mang-luoi-toan-cau.html"',
    'href="../corporate-services.html"': 'href="dich-vu-doanh-nghiep.html"',
    'href="singapore.html"': 'href="thanh-lap-cong-ty-singapore.html"',
    'href="the-us.html"': 'href="thanh-lap-cong-ty-my.html"',
    'href="hong-kong.html"': 'href="thanh-lap-cong-ty-hong-kong.html"',
    'href="../china-korea-market-entry.html"': 'href="tham-nhap-thi-truong-trung-han.html"',
    'href="../accounting-payment-solutions.html"': 'href="giai-phap-ke-toan-thanh-toan.html"',
    'href="../logistics-export.html"': 'href="logistics-xuat-khau.html"',
    'href="../sourcing-import.html"': 'href="mua-ho-nhap-khau.html"',
    'href="../tracking.html"': 'href="tra-cuu.html"',
    'href="../contact-us.html"': 'href="lien-he.html"',
    'href="../index.html"': 'href="index.html"',
    'href="../vi/index.html"': 'href="#" class="lang-active" style="pointer-events: none;"', 
    'href="index.html" aria-current="true"': 'href="../../en/company-incorporation/singapore.html"',
    # CSS/JS/Images
    '../../': '../',
    'class="site-default navigation-navigationen theme-default layout-homeen': 'class="site-default navigation-navigationvi theme-default layout-homevi' 
}

try:
    with open(src, 'r', encoding='utf-8') as f:
        content = f.read()

    # Apply link map first
    for k, v in link_map.items():
        content = content.replace(k, v)

    # Apply text replacements
    for k, v in replacements.items():
        content = content.replace(k, v)

    with open(dst, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print(f"Translated file written to {dst}")
    
except Exception as e:
    print(f"Error: {e}")
